baseURL = "https://mfasiolo.github.io/sc2-2019/"
languageCode = "en-us"
title = "SC2"

theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Interfacing R with C/C++"
    url = "/rcpp/"
    weight = 2
[[menu.main]]
    name = "Advanced Rcpp"
    url = "/rcpp_advanced/"
    weight = 3

[params]
    description = "Statistical Computing 2"
    footer = "&copy; 2019 [Matteo Fasiolo](https://mfasiolo.github.io/)"
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"
    GithubEdit = "https://github.com/mfasiolo/sc2-2019/edit/master/content/"
    GithubView = "https://github.com/mfasiolo/sc2-2019/blob/master/content/"
